import { ChainConfig, ChainId } from "../types";

export const CHAIN_CONFIGS: Record<ChainId, ChainConfig> = {
  osmosis: {
    id: "osmosis",
    name: "Osmosis",
    displayName: "Osmosis",
    icon: "/chains/osmosis.svg",
    color: "#9D4EDD",
    gradientFrom: "#9D4EDD",
    gradientTo: "#C77DFF",
    addressPrefix: "osmo",
    addressRegex: /^osmo[a-z0-9]{39}$/i,
    testAddress: "osmo1g8gv8ayl55698fscstajt9uqw9r6w8a34aly9v",
    rpcEndpoints: [
      "https://rpc.osmosis.zone",
      "https://osmosis-rpc.polkachu.com",
      "https://osmosis-rpc.publicnode.com",
    ],
    apiEndpoints: [
      "https://lcd.osmosis.zone",
      "https://osmosis-api.polkachu.com",
      "https://api.osmosis.interbloc.org",
    ],
    explorerUrl: "https://www.mintscan.io/osmosis/tx",
    apiKey: null, // Public endpoints
    decimals: 6,
    nativeDenom: "uosmo",
    nativeSymbol: "OSMO",
    enabled: false,
    description: "Cosmos DEX and DeFi hub (Coming soon)",
  },
  babylon: {
    id: "babylon",
    name: "Babylon",
    displayName: "Babylon",
    icon: "/chains/babylon.svg",
    color: "#CE6533",
    gradientFrom: "#CE6533",
    gradientTo: "#E8845A",
    addressPrefix: "bbn",
    addressRegex: /^bbn[a-z0-9]{39}$/i,
    testAddress: "bbn1e5h88h7lw6d6d9x9zg5v0p4j7t9z5q0n9s0d8e",
    rpcEndpoints: [
      "https://babylon-mainnet-rpc.allthatnode.com:26657/edb5b9348fb34b33855da007fcafebae",
      "https://babylon-mainnet.g.allthatnode.com/full/tendermint/edb5b9348fb34b33855da007fcafebae",
    ],
    apiEndpoints: [
      "https://babylon-mainnet.g.allthatnode.com/full/rest/edb5b9348fb34b33855da007fcafebae",
    ],
    explorerUrl: "https://babylon.explorers.guru/transaction",
    apiKey: "edb5b9348fb34b33855da007fcafebae",
    decimals: 6,
    nativeDenom: "ubbn",
    nativeSymbol: "BABY",
    enabled: false,
    description: "Bitcoin staking protocol on Cosmos (Coming soon)",
  },
  // Placeholders for future chains
  near: {
    id: "near",
    name: "NEAR",
    displayName: "NEAR Protocol",
    icon: "/chains/near.svg",
    color: "#00C08B",
    gradientFrom: "#00C08B",
    gradientTo: "#00E8A7",
    addressPrefix: "",
    addressRegex: /^(?:[a-z0-9_-]+(?:\.[a-z0-9_-]+)*|[a-f0-9]{64})$/i,
    testAddress: "alice.near",
    rpcEndpoints: [
      "https://near-mainnet.g.allthatnode.com/full/json_rpc/edb5b9348fb34b33855da007fcafebae",
    ],
    apiEndpoints: ["https://api.pikespeak.ai"],
    explorerUrl: "https://nearblocks.io/txns",
    apiKey: "3847be2e-2f13-48ec-86fd-e5d1751fcb09",
    decimals: 24,
    nativeDenom: "",
    nativeSymbol: "NEAR",
    enabled: false,
    description: "Scalable L1 blockchain with fast transactions (Coming soon)",
  },
  polkadot: {
    id: "polkadot",
    name: "Polkadot",
    displayName: "Polkadot",
    icon: "/chains/polkadot.svg",
    color: "#E6007A",
    gradientFrom: "#E6007A",
    gradientTo: "#FF2B9C",
    addressPrefix: "1",
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{47,48}$/,
    testAddress: "14DzQhcj2hNuprLiY7y5x3Jt5kQ5Z5Q5Z5Q5Z5Q5Z5Q5Z5",
    rpcEndpoints: [
      "https://polkadot-mainnet.g.allthatnode.com/full/json_rpc/edb5b9348fb34b33855da007fcafebae",
    ],
    apiEndpoints: [],
    explorerUrl: "https://polkadot.subscan.io/extrinsic",
    apiKey: "edb5b9348fb34b33855da007fcafebae",
    decimals: 10,
    nativeDenom: "",
    nativeSymbol: "DOT",
    enabled: false, // Coming soon
    description: "Multi-chain network (Coming soon)",
  },
  celo: {
    id: "celo",
    name: "CELO",
    displayName: "Celo",
    icon: "https://s2.coinmarketcap.com/static/img/coins/200x200/5567.png",
    color: "#FCFF52",
    gradientFrom: "#FCFF52",
    gradientTo: "#35D07F",
    addressPrefix: "0x",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    testAddress: "0xD23Bfd31430eFB9c8358b703B62BdE17F36E1274",
    rpcEndpoints: [],
    apiEndpoints: ["https://api.etherscan.io/v2/api"],
    explorerUrl: "https://celoscan.io/tx",
    apiKey: "39SMAR4FE2B41TQI5MDQ4PNDM5BG4HSP7J",
    decimals: 18,
    nativeDenom: "",
    nativeSymbol: "CELO",
    enabled: true,
    description: "Mobile-first blockchain for DeFi (via Etherscan v2 API)",
  },
  fantom: {
    id: "fantom",
    name: "Fantom",
    displayName: "Fantom",
    icon: "/chains/fantom.svg",
    color: "#1969FF",
    gradientFrom: "#1969FF",
    gradientTo: "#13B5EC",
    addressPrefix: "0x",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    testAddress: "0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73",
    rpcEndpoints: ["https://fantom-mainnet.gateway.tatum.io/"],
    apiEndpoints: ["https://api.tatum.io/v4/data/transactions"],
    explorerUrl: "https://ftmscan.com/tx",
    apiKey: "t-697d4031ace70350f2245030-4a6be09c40b84989bb00c1c8",
    decimals: 18,
    nativeDenom: "",
    nativeSymbol: "FTM",
    enabled: false,
    description: "High-performance EVM chain (Coming soon)",
  },
  flow: {
    id: "flow",
    name: "Flow",
    displayName: "Flow",
    icon: "/chains/flow.svg",
    color: "#00EF8B",
    gradientFrom: "#00EF8B",
    gradientTo: "#47FFB8",
    addressPrefix: "0x",
    addressRegex: /^0x[a-fA-F0-9]{16}$/,
    testAddress: "0x1654653399040a61",
    rpcEndpoints: [
      "https://flow-mainnet.g.allthatnode.com/full/json_rpc/edb5b9348fb34b33855da007fcafebae",
    ],
    apiEndpoints: ["https://rest-mainnet.onflow.org"],
    explorerUrl: "https://flowscan.org/transaction",
    apiKey: "edb5b9348fb34b33855da007fcafebae",
    decimals: 8,
    nativeDenom: "",
    nativeSymbol: "FLOW",
    enabled: false, // Coming soon
    description: "NFT and gaming chain (Coming soon)",
  },
  ronin: {
    id: "ronin",
    name: "Ronin",
    displayName: "Ronin",
    icon: "https://s3.coinmarketcap.com/static/img/as/2025-01-17T15:38:45.123Z_ronin_ron_logo.png",
    color: "#1273EA",
    gradientFrom: "#1273EA",
    gradientTo: "#00B8D4",
    addressPrefix: "0x",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    testAddress: "0x267c406d26a4b43614df329d4f2ae6773cb630b2",
    rpcEndpoints: [],
    apiEndpoints: ["https://api.covalenthq.com/v1"],
    explorerUrl: "https://app.roninchain.com/tx",
    apiKey: "cqt_rQX6pj3BJWcjjPWd7pWwgTDvk8PQ",
    decimals: 18,
    nativeDenom: "",
    nativeSymbol: "RON",
    enabled: true,
    description: "Gaming-focused EVM chain (Axie Infinity)",
  },
  celestia: {
    id: "celestia",
    name: "Celestia",
    displayName: "Celestia",
    icon: "https://cryptologos.cc/logos/celestia-tia-logo.png",
    color: "#0074E4",
    gradientFrom: "#0074E4",
    gradientTo: "#00A8E8",
    addressPrefix: "celestia",
    addressRegex: /^celestia[a-z0-9]{39}$/i,
    testAddress: "celestia18hrx28j3gadsjw67gcuu7wmwfxtm42ehg2awt2",
    rpcEndpoints: [],
    apiEndpoints: ["https://api-mainnet.celenium.io/v1"],
    explorerUrl: "https://celestia.explorers.guru/transaction",
    apiKey: null,
    decimals: 6,
    nativeDenom: "utia",
    nativeSymbol: "TIA",
    enabled: true,
    description: "Data availability layer for modular blockchains",
  },
  tezos: {
    id: "tezos",
    name: "Tezos",
    displayName: "Tezos",
    icon: "https://thegivingblock.com/wp-content/uploads/2025/04/67f393c22a1c.png",
    color: "#2C7DF7",
    gradientFrom: "#2C7DF7",
    gradientTo: "#4CABFF",
    addressPrefix: "tz1",
    addressRegex: /^(tz1|tz2|tz3)[1-9A-Za-z]{33}$/,
    testAddress: "tz1daLg7rrK5msfvPkxDNTdEeYdp73qmjD8t",
    rpcEndpoints: [],
    apiEndpoints: ["https://api.tzkt.io/v1"],
    explorerUrl: "https://tzkt.io",
    apiKey: null,
    decimals: 6,
    nativeDenom: "mutez",
    nativeSymbol: "XTZ",
    enabled: true,
    description: "Self-amending blockchain with on-chain governance (via TzKT API)",
  },
};

export const ENABLED_CHAINS = Object.values(CHAIN_CONFIGS).filter(
  (c) => c.enabled,
);

export function getChainConfig(chainId: ChainId): ChainConfig {
  const config = CHAIN_CONFIGS[chainId];
  if (!config) {
    throw new Error(`Unknown chain: ${chainId}`);
  }
  return config;
}

export function isChainEnabled(chainId: ChainId): boolean {
  return CHAIN_CONFIGS[chainId]?.enabled ?? false;
}

export const DEFAULT_CHAIN: ChainId = "osmosis";
